#!/usr/bin/env python3
"""
Scans ForFeralSake/Textures/ folder and generates TextureManifest.lua
Run this after adding new .tga or .blp files to the Textures folder.

Usage:
    python generate_manifest.py
    python generate_manifest.py --convert   (also converts any .png/.jpg to .tga)
"""

import os
import sys
import glob

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TEXTURES_DIR = os.path.join(SCRIPT_DIR, "Textures")
MANIFEST_PATH = os.path.join(SCRIPT_DIR, "TextureManifest.lua")
ADDON_NAME = "ForFeralSake"
VALID_EXT = {".tga", ".blp"}
CONVERTIBLE_EXT = {".png", ".jpg", ".jpeg", ".bmp"}


def next_pow2(n):
    p = 1
    while p < n:
        p *= 2
    return p


def convert_images():
    try:
        from PIL import Image
    except ImportError:
        print("Pillow not installed. Run: pip install Pillow")
        return

    for root, dirs, files in os.walk(TEXTURES_DIR):
        for f in files:
            ext = os.path.splitext(f)[1].lower()
            if ext in CONVERTIBLE_EXT:
                src = os.path.join(root, f)
                dst = os.path.splitext(src)[0] + ".tga"
                if os.path.exists(dst):
                    print(f"  Skip (already exists): {dst}")
                    continue
                img = Image.open(src).convert("RGBA")
                w, h = img.size
                new_w = min(next_pow2(w), 1024)
                new_h = min(next_pow2(h), 1024)
                if (new_w, new_h) != (w, h):
                    img = img.resize((new_w, new_h), Image.LANCZOS)
                img.save(dst, format="TGA")
                print(f"  Converted: {f} -> {os.path.basename(dst)} ({new_w}x{new_h})")


def scan_textures():
    entries = []
    for root, dirs, files in os.walk(TEXTURES_DIR):
        for f in sorted(files):
            ext = os.path.splitext(f)[1].lower()
            if ext not in VALID_EXT:
                continue
            full = os.path.join(root, f)
            rel = os.path.relpath(full, SCRIPT_DIR).replace("\\", "/")
            wow_path = f"Interface\\\\AddOns\\\\{ADDON_NAME}\\\\" + rel.replace("/", "\\\\")
            name = os.path.splitext(f)[0]
            subdir = os.path.relpath(root, TEXTURES_DIR).replace("\\", "/")
            if subdir == ".":
                display = name
            else:
                display = f"{subdir}/{name}"
            entries.append((display, wow_path))
    return entries


def generate_lua(entries):
    lines = [
        f'local addonName, FFS = ...',
        f'',
        f'-- Auto-generated by generate_manifest.py',
        f'-- Do not edit manually. Re-run the script after adding textures.',
        f'',
        f'FFS.TextureManifest = {{',
    ]
    for display, path in entries:
        lines.append(f'    {{ name = "{display}", path = "{path}" }},')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    do_convert = "--convert" in sys.argv

    if do_convert:
        print("Converting images...")
        convert_images()

    print("Scanning textures...")
    entries = scan_textures()
    print(f"  Found {len(entries)} texture(s)")

    lua = generate_lua(entries)
    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        f.write(lua)
    print(f"Generated: {MANIFEST_PATH}")

    # Also copy to addon folder if it exists
    addon_dir = None
    for candidate in [
        os.path.join("D:\\WOW\\China\\_retail_\\Interface\\AddOns", ADDON_NAME),
    ]:
        if os.path.isdir(candidate):
            addon_dir = candidate
            break

    if addon_dir:
        import shutil
        dst = os.path.join(addon_dir, "TextureManifest.lua")
        shutil.copy2(MANIFEST_PATH, dst)
        print(f"Deployed: {dst}")

        # Also copy texture files
        tex_dst = os.path.join(addon_dir, "Textures")
        os.makedirs(tex_dst, exist_ok=True)
        for root, dirs, files in os.walk(TEXTURES_DIR):
            for f in files:
                ext = os.path.splitext(f)[1].lower()
                if ext in VALID_EXT:
                    src = os.path.join(root, f)
                    rel = os.path.relpath(src, TEXTURES_DIR)
                    out = os.path.join(tex_dst, rel)
                    os.makedirs(os.path.dirname(out), exist_ok=True)
                    shutil.copy2(src, out)
        print(f"Textures deployed to: {tex_dst}")


if __name__ == "__main__":
    main()
