local addonName, FFS = ...

-- Auto-generated by generate_manifest.py
-- Do not edit manually. Re-run the script after adding textures.

FFS.TextureManifest = {
    { name = "Backgrounds/yujie", path = "Interface\\AddOns\\ForFeralSake\\Textures\\Backgrounds\\yujie.tga" },
}
